config/routes.rb
require 'sidekiq/web'

GitlabCi::Application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resource :help

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status, to: 'projects#badge'
      get :integration
      post :build
    end

    resource :charts, only: [:show]
    resources :commits, only: [:show] do
      member do
        get :status
      end
    end

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :web_hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end
  end

  resource :user_sessions

  namespace :admin do
    resources :runners, only: [:index, :show, :update, :destroy] do
      member do
        put :assign_all
      end
    end

    resources :projects do
      resources :runner_projects
    end

    resources :builds, only: :index
  end

  root :to => 'projects#index'
end

app/models/commit.rb
# == Schema Information
#
# Table name: commits
#
#  id         :integer          not null, primary key
#  project_id :integer
#  ref        :string(255)
#  sha        :string(255)
#  before_sha :string(255)
#  push_data  :text
#  created_at :datetime
#  updated_at :datetime
#

class Commit < ActiveRecord::Base
  belongs_to :project
  has_many :builds
  has_many :jobs, through: :builds

  serialize :push_data

  validates_presence_of :ref, :sha, :before_sha, :push_data
  validate :valid_commit_sha

  def self.truncate_sha(sha)
    sha[0...8]
  end

  def to_param
    sha
  end

  def last_build
    builds.last
  end

  def valid_commit_sha
    if self.sha == Git::BLANK_SHA
      self.errors.add(:sha, " cant be 00000000 (branch removal)")
    end
  end

  def new_branch?
    before_sha == Git::BLANK_SHA
  end

  def compare?
    gitlab? && !new_branch?
  end

  def gitlab?
    project.gitlab?
  end

  def ci_skip?
    !!(git_commit_message =~ /(\[ci skip\])/)
  end

  def git_author_name
    commit_data[:author][:name] if commit_data && commit_data[:author]
  end

  def git_author_email
    commit_data[:author][:email] if commit_data && commit_data[:author]
  end

  def git_commit_message
    commit_data[:message] if commit_data && commit_data[:message]
  end

  def short_before_sha
    Commit.truncate_sha(before_sha)
  end

  def short_sha
    Commit.truncate_sha(sha)
  end

  def commit_data
    push_data[:commits].find do |commit|
      commit[:id] == sha
    end
  rescue
    nil
  end

  def project_recipients
    recipients = project.email_recipients.split(' ')
    recipients << git_author_email if project.email_add_committer?
    recipients.uniq
  end

  def create_builds
    project.jobs.active.map do |job|
      build = builds.new(commands: job.commands)
      build.job = job
      build.save
      build
    end
  end

  def builds_without_retry
    @builds_without_retry ||=
      begin
        grouped_builds = builds.group_by(&:job)
        grouped_builds.map do |job, builds|
          builds.sort_by(&:id).last
        end
      end
  end

  def retried_builds
    @retried_builds ||= (builds - builds_without_retry)
  end

  def status
    if success?
      'success'
    elsif pending?
      'pending'
    elsif running?
      'running'
    elsif canceled?
      'canceled'
    else
      'failed'
    end
  end

  def pending?
    builds_without_retry.all? do |build|
      build.pending?
    end
  end

  def running?
    builds_without_retry.any? do |build|
      build.running? || build.pending?
    end
  end

  def success?
    builds_without_retry.all? do |build|
      build.success?
    end
  end

  def failed?
    status == 'failed'
  end

  def canceled?
    builds_without_retry.all? do |build|
      build.canceled?
    end
  end

  def duration
    @duration ||= builds_without_retry.select(&:duration).sum(&:duration).to_i
  end

  def finished_at
    @finished_at ||= builds.order('finished_at ASC').first.try(:finished_at)
  end

  def coverage
    if project.coverage_enabled? && builds.size == 1
      builds.first.coverage
    end
  end

  def matrix?
    builds_without_retry.size > 1
  end
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  before_filter :authenticate_user!, except: [:status]
  before_filter :project
  before_filter :commit
  before_filter :authorize_access_project!, except: [:status]

  def show
    @builds = @commit.builds
  end

  def status
    render json: @commit.to_json(only: [:id, :sha], methods: [:status, :coverage])
  end

  private

  def project
    @project ||= Project.find(params[:project_id])
  end

  def commit
    @commit ||= project.commits.find_by(sha: params[:id])
  end
end

app/helpers/commits_helper.rb
module CommitsHelper
  def commit_status_alert_class(commit)
    return unless commit

    case commit.status
    when 'success'
      'alert-success'
    when 'failed', 'canceled'
      'alert-danger'
    else
      'alert-warning'
    end
  end

  def commit_link(commit)
    link_to(commit.short_sha, project_commit_path(commit.project, commit))
  end
end

app/views/commits/_commit.html.haml
%tr.build.alert{class: commit_status_alert_class(commit)}
  %td.status
    = commit.status

  %td.build-link
    = link_to project_commit_path(commit.project, commit) do
      %strong #{commit.short_sha}

  %td.build-message
    %span= truncate(commit.git_commit_message, length: 50)

  %td.build-branch
    - unless @ref
      %span
        = link_to truncate(commit.ref, length: 25), project_path(@project, ref: commit.ref)

  %td.duration
    - if commit.duration > 0
      #{distance_of_time_in_words commit.duration}

  %td.timestamp
    - if commit.finished_at
      %span #{time_ago_in_words commit.finished_at} ago

  - if commit.project.coverage_enabled?
    %td.coverage
      - if commit.coverage
        #{commit.coverage}%

app/views/commits/show.html.haml
%h4.page-title
  = @project.name
  @
  #{gitlab_commit_link(@project, @commit.sha)}
  .pull-right
    = link_to edit_project_path(@project), class: "btn btn-default btn-small" do
      %i.icon-edit.icon-white
      Edit Project

%p
  = link_to project_path(@project) do
    &larr; Back to project commits
%hr
.commit-info
  %pre.commit-message
    #{@commit.git_commit_message}

  .row
    .col-sm-6
      - if @commit.compare?
        %p
          %span.attr-name Compare:
          #{gitlab_compare_link(@project, @commit.short_before_sha, @commit.short_sha)}
      - else
        %p
          %span.attr-name Commit:
          #{gitlab_commit_link(@project, @commit.sha)}

      %p
        %span.attr-name Branch:
        #{gitlab_ref_link(@project, @commit.ref)}
    .col-sm-6
      %p
        %span.attr-name Author:
        #{@commit.git_author_name} (#{@commit.git_author_email})
      - if @commit.created_at
        %p
          %span.attr-name Created at:
          #{@commit.created_at.to_s(:short)}


%h3 Status

.build.alert{class: commit_status_alert_class(@commit)}
  .status
    = @commit.status.titleize

%h3
  Builds
  - if @commit.duration > 0
    %small.pull-right
      %i.icon-time
      #{distance_of_time_in_words @commit.duration}

%table.builds
  %thead
    %tr
      %th Status
      %th Build ID
      %th Job
      %th Duration
      %th Finished at
      - if @project.coverage_enabled?
        %th Coverage
      %th
  = render @commit.builds_without_retry, controls: true

- if @commit.retried_builds.any?
  %h3
    Retried builds

  %table.builds
    %thead
      %tr
        %th Status
        %th Build ID
        %th Job
        %th Duration
        %th Finished at
        - if @project.coverage_enabled?
          %th Coverage
        %th
    = render @commit.retried_builds